In [1]:
import torch
import pandas as pd

In [17]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-1.0743,  0.0983, -1.2875], requires_grad=True)


In [18]:
# let's perform some operation on x. This creates an operational DAG,
# where the inputs are 2 and x into a DAG operator +, and the output
# is y. As a result of requires_grad=True, PyTorch will create a gradient
# function, grad_fn, for us, to be used for backprogration. Forward propogation has
# has two inputs (x, 2); backward propogation is derivatie of f(x)
y = x + 2
print(y)

tensor([0.9257, 2.0983, 0.7125], grad_fn=<AddBackward0>)


In [19]:
# some more operations 
z = y * y * 2
print(z)
z = z.mean()
print(z)

tensor([1.7138, 8.8060, 1.0154], grad_fn=<MulBackward0>)
tensor(3.8450, grad_fn=<MeanBackward0>)


In [20]:
z.backward() # calculates the gradient dz/dx 
print(x.grad)

tensor([1.2342, 2.7978, 0.9500])


### Three options to disable grad_fun
1. x.require_grad_(False)
2. x.detach()
3. use a with statement

In [21]:
x = torch.randn(3, requires_grad=True)
x.requires_grad_(False)

tensor([-0.2579, -0.2586, -1.4217])

In [22]:
y = x.detach()
print(y)

tensor([-0.2579, -0.2586, -1.4217])


In [23]:
with torch.no_grad():
    y = x + 2
    print(y)

tensor([1.7421, 1.7414, 0.5783])


### Some training examples

In [35]:
weights = torch.ones(4, requires_grad=True)
for epochs in range(3):
    model_output = (weights * 3).sum()
    
    # compute the backward gradients
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
