In [42]:
import torch
import numpy as np

In [3]:
# create two rand 2 x 2 tensors 
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.5928, 0.4515],
        [0.3077, 0.2707]])
tensor([[0.1627, 0.9713],
        [0.5293, 0.6913]])


In [24]:
data= [[1, 2, 3],
       [4, 5, 6]]

data2 = [7, 9., 12.34]

# factory method that returns a copy of data
t1 = torch.tensor(data) # infers dtype from the data

# factory method that shares the data and can accept any Python like array data type
t2 = torch.as_tensor(data) # infers dype from the data
tl = torch.as_tensor(data2)
# Constructor the create a new copy of data\
t3 = torch.Tensor(data) # use the global default float32

print(t1, t1.dtype, t1.shape, t1.dim())
print(t2, t2.dtype, t2.shape)
print(t3, t3.dtype, t3.shape)
print(tl, tl.dtype, tl.shape, tl.dim(), tl[0].item())
t1[0][1].item()
t1.numel()
tl.numel()

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.int64 torch.Size([2, 3]) 2
tensor([[1, 2, 3],
        [4, 5, 6]]) torch.int64 torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.float32 torch.Size([2, 3])
tensor([ 7.0000,  9.0000, 12.3400]) torch.float32 torch.Size([3]) 1 7.0


3

### Tensor torch common math operatitons:add, sub, mul, div etc

In [7]:
# do element wise addition of the two tensors
z = x + y
print(z)

tensor([[1.6898, 0.2364],
        [1.0545, 0.5296]])


In [8]:
z = torch.add(x,y)
print(z)

tensor([[1.6898, 0.2364],
        [1.0545, 0.5296]])


In [9]:
# do element wise tensor multiplication
m = x * y
print(m)

tensor([[0.7020, 0.0133],
        [0.2663, 0.0182]])


In [10]:
m = torch.mul(x,y)
print(m)

tensor([[0.7020, 0.0133],
        [0.2663, 0.0182]])


In [11]:
# do element wise division
d = x / y
print(d)

tensor([[0.7719, 1.5894],
        [1.5161, 0.0749]])


In [13]:
d = torch.div(x,y)
print(d)

tensor([[0.7719, 1.5894],
        [1.5161, 0.0749]])


In [14]:
s = x - y
print(s)

tensor([[-0.2175,  0.0538],
        [ 0.2163, -0.4558]])


In [16]:
s = torch.sub(x,y)
print(s)

tensor([[-0.2175,  0.0538],
        [ 0.2163, -0.4558]])


In [132]:
t1 = torch.tensor([[1, 2],
                   [3, 4]
                 ], dtype=torch.float32)
t1

tensor([[1., 2.],
        [3., 4.]])

In [133]:
t2 = torch.tensor([[9, 8],
                   [7, 6]], dtype=torch.float32)
t2

tensor([[9., 8.],
        [7., 6.]])

In [134]:
# example from the first axis
t1[0]

tensor([1., 2.])

In [135]:
# example from the second axis
t1[0][0]

tensor(1.)

In [136]:
# Elementwise operations dictate that two tensors are of the same shape
# each tensor element within the first tensor has the corrosponding element
# in the second tensor via the same indices
t1[0][0], t2[0][0]

(tensor(1.), tensor(9.))

In [138]:
# They all addup to 10. Addition is an elementwise operation
t3 = t1 + t2
t3, t3.shape

(tensor([[10., 10.],
         [10., 10.]]),
 torch.Size([2, 2]))

In [139]:
# this a scalar operation with tensor of rank-2. This general
# rule will broadcast scalar 2 as 2-d tendor [[2,2], [2,2]] 
# and then peform an element wise addtion
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [ ]:
# let's understand broadcast with another example

In [152]:
t = torch.tensor([
    [1, 1],
    [1, 1]], dtype=torch.float32)
t, t.shape

(tensor([[1., 1.],
         [1., 1.]]),
 torch.Size([2, 2]))

In [153]:
t2 = torch.tensor([2, 4], dtype=torch.float32)
t2, t2.shape

(tensor([2., 4.]), torch.Size([2]))

In [148]:
np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [154]:
# Even though t1 and t2 are of different shapes, we still did an element wise operation
# The reason it worked is because the lower rank tensor t2 is prompted to a 2-d tensor
# and broadcasted as t2 = [[2,4], [2, 4]]

t1 + t2

tensor([[3., 6.],
        [5., 8.]])

In [155]:
t2 + t1

tensor([[3., 6.],
        [5., 8.]])

In [156]:
torch.add(t1, t2)

tensor([[3., 6.],
        [5., 8.]])

In [160]:
# comparison operations
t = torch.tensor([
    [0, 5, 7],
    [6, 0, 7],
    [0, 8, 0]
], dtype=torch.float32)
t

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [161]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [162]:
t.gt(0)

tensor([[False,  True,  True],
        [ True, False,  True],
        [False,  True, False]])

In [163]:
t.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [164]:
t.lt(7)

tensor([[ True,  True, False],
        [ True,  True, False],
        [ True, False,  True]])

In [165]:
t.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [166]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [170]:
t.sum(), t.mean()

(tensor(33.), tensor(3.6667))

In [171]:
t.min(), t.max()

(tensor(0.), tensor(8.))

In [172]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

### ArgMax and Reduction functions

In [175]:
# A reducion operation on a tensor reduces the number of elements in a tensor
t = torch.tensor([
    [0, 1, 0],
    [2, 0, 2],
    [0, 3, 0]
], dtype=torch.float32)
t

tensor([[0., 1., 0.],
        [2., 0., 2.],
        [0., 3., 0.]])

In [176]:
# Sum is a reduction operation
t.sum()

tensor(8.)

In [177]:
t.numel()

9

In [178]:
t.sum().numel()

1

In [179]:
t.sum().numel() < t.numel()

True

In [ ]:
# Other reduction operations are min(), max(), mean(), std

In [180]:
t.mean(), t.std(), t.min(), t.max()

(tensor(0.8889), tensor(1.1667), tensor(0.), tensor(3.))

In [186]:
# Reduction method across tensor dimensions
t = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3]
], dtype=torch.float32)
t, t.shape

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.]]),
 torch.Size([3, 4]))

In [184]:
# down the first axis down the column dim=0 return 4 values since we have 4 columns
# That is a 1-d tensor with 4 elements
t.sum(dim=0), t.sum(dim=0).shape

(tensor([6., 6., 6., 6.]), torch.Size([4]))

In [185]:
# across the each row dim=1 along the second axis, across each row
# that is a 1-d tensor with 3 elements 
t.sum(dim=1), t.sum(dim=1).shape

(tensor([ 4.,  8., 12.]), torch.Size([3]))

In [187]:
# ArgMax
t = torch.tensor([
    [1, 0, 0, 2],
    [0, 3, 3, 0],
    [4, 0, 0, 5]
], dtype=torch.float32)
t, t.shape

(tensor([[1., 0., 0., 2.],
         [0., 3., 3., 0.],
         [4., 0., 0., 5.]]),
 torch.Size([3, 4]))

In [194]:
t.max()

tensor(5.)

In [195]:
t.argmax()

tensor(11)

In [200]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [201]:
t.max(dim=0) # across columns

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [202]:
t.argmax(dim=0) # down the column

tensor([2, 1, 1, 2])

In [203]:
t.max(dim=1) # across the second axis rows

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 2, 3]))

In [206]:
t.sum(dim=0) # down the column, 4 values since we have 4 columns

tensor([5., 3., 3., 7.])

In [207]:
t.mean(dim=0) # down the column, 4 values since we have 4 columns

tensor([1.6667, 1.0000, 1.0000, 2.3333])

In [209]:
t.sum(dim=1) # across rows, 3 values since we have 3 rows

tensor([3., 6., 9.])

In [211]:
t.mean(dim=1) 

tensor([0.7500, 1.5000, 2.2500])

### Common slice operations

In [157]:
t1, t2


(tensor([[1., 2.],
         [3., 4.]]),
 tensor([2., 4.]))

In [158]:
torch.add(t2, t1)

tensor([[3., 6.],
        [5., 8.]])

In [17]:
x = torch.rand(5,3)
print(x)

tensor([[0.2846, 0.3282, 0.1154],
        [0.7743, 0.7224, 0.5586],
        [0.5214, 0.3714, 0.5913],
        [0.8415, 0.3570, 0.7835],
        [0.8826, 0.3503, 0.9242]])


In [18]:
# print all rows and only the 0th column
print(x[:, 0])

tensor([0.2846, 0.7743, 0.5214, 0.8415, 0.8826])


In [23]:
# print all only row 1 and all columns
print(x[1, :])

tensor([0.7743, 0.7224, 0.5586])


In [21]:
# index into elemen [1,1], returns a tensor
# .item() returns the value. You can only use item() on a tensor with a single value
print(x[1,1])
print(x[1,1].item())

tensor(0.7224)
0.722439706325531


### Reshaping a tensor

In [43]:
# tensor with 2-axes. first axis (rows as the length of 4)
# second axis - columns has a length of 3
t = torch.tensor([ [1, 1, 1 ,1],
                   [2, 2, 2, 2],
                   [3, 3, 3, 3]], dtype=torch.float32)
t, t.shape, t.size(), len(t.shape)

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.]]),
 torch.Size([3, 4]),
 torch.Size([3, 4]),
 2)

In [46]:
# number of elements in a tensor
t.numel(), torch.tensor(t.shape).prod().item()

(12, 12)

In [47]:
t.numel() == torch.tensor(t.shape).prod().item()

True

In [54]:
# reshaping the tensor must account for all 12 elements. That is, the rows and columns must 
# be a factor of 12: (12, 1), (4, 3), (3, 4), (2, 6), (6, 2)
t.reshape(12,1), t.reshape(1,12)

(tensor([[1.],
         [1.],
         [1.],
         [1.],
         [2.],
         [2.],
         [2.],
         [2.],
         [3.],
         [3.],
         [3.],
         [3.]]),
 tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]]),
 tensor([[1., 1., 1.],
         [1., 2., 2.],
         [2., 2., 3.],
         [3., 3., 3.]]))

In [55]:
t.reshape(4, 3),  t.reshape( 4, 3)

(tensor([[1., 1., 1.],
         [1., 2., 2.],
         [2., 2., 3.],
         [3., 3., 3.]]),
 tensor([[1., 1., 1.],
         [1., 2., 2.],
         [2., 2., 3.],
         [3., 3., 3.]]))

In [56]:
t.reshape(2, 6), t.reshape(6, 2)

(tensor([[1., 1., 1., 1., 2., 2.],
         [2., 2., 3., 3., 3., 3.]]),
 tensor([[1., 1.],
         [1., 1.],
         [2., 2.],
         [2., 2.],
         [3., 3.],
         [3., 3.]]))

In [63]:
# another way to reshape is add another factor
t.reshape(2, 2, 3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [76]:
# You can also use squeeze and unsqueeze operations
# Squeeze removes all of the axes with a length of 1
ts = t.reshape(1,12)
ts, ts.shape

(tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]]),
 torch.Size([1, 12]))

In [75]:
ts.squeeze(), ts.squeeze().shape

(tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]), torch.Size([12]))

In [79]:
# unsqueeze adds another dimension with a length of 1
ts = t.reshape(1,12).squeeze()
ts

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [88]:
# add an axes along dimension 0, which is row
ts.unsqueeze(dim=0), ts.unsqueeze(dim=0).shape

(tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]]),
 torch.Size([1, 12]))

In [90]:
# add an axes along dimension 1, which is column
ts.unsqueeze(dim=1), ts.unsqueeze(dim=1).shape

(tensor([[1.],
         [1.],
         [1.],
         [1.],
         [2.],
         [2.],
         [2.],
         [2.],
         [3.],
         [3.],
         [3.],
         [3.]]),
 torch.Size([12, 1]))

In [91]:
def flatten(t):
    t = t.reshape(1, -1)
    t = t.squeeze()
    return t

In [93]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [95]:
t1 = torch.tensor([ [1, 1, 1, 1],
                    [1, 1, 1, 1],
                    [1, 1, 1, 1],
                    [1, 1, 1, 1]])
t1, t1.shape

(tensor([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]),
 torch.Size([4, 4]))

In [96]:
t2 = torch.tensor([ [2, 2, 2, 2],
                    [2, 2, 2, 2],
                    [2, 2, 2, 2],
                    [2, 2, 2, 2]])
t2, t2.shape

(tensor([[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]]),
 torch.Size([4, 4]))

In [97]:
t3 = torch.tensor([ [3, 3, 3, 3],
                    [3, 3, 3, 3],
                    [3, 3, 3, 3],
                    [3, 3, 3, 3]])
t3, t3.shape

(tensor([[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]),
 torch.Size([4, 4]))

In [104]:
# create a batch of 3 tensors
tb = torch.stack((t1, t2, t3))
tb, tb.shape, len(tb.shape)

(tensor([[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]],
 
         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],
 
         [[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]),
 torch.Size([3, 4, 4]),
 3)

In [ ]:
# add a color channel by reshaping

In [108]:
tb = tb.reshape(3, 1, 4, 4)
tb, tb.shape, len(tb.shape)

(tensor([[[[1, 1, 1, 1],
           [1, 1, 1, 1],
           [1, 1, 1, 1],
           [1, 1, 1, 1]]],
 
 
         [[[2, 2, 2, 2],
           [2, 2, 2, 2],
           [2, 2, 2, 2],
           [2, 2, 2, 2]]],
 
 
         [[[3, 3, 3, 3],
           [3, 3, 3, 3],
           [3, 3, 3, 3],
           [3, 3, 3, 3]]]]),
 torch.Size([3, 1, 4, 4]),
 4)

In [111]:
# first image
tb[0], tb[0].shape

(tensor([[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]]),
 torch.Size([1, 4, 4]))

In [112]:
# first color channel in the first image
tb[0][0], tb[0][0].shape

(tensor([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]),
 torch.Size([4, 4]))

In [113]:
# first row of pixels of the first color channel of the first image
tb[0][0][0], tb[0][0][0].shape

(tensor([1, 1, 1, 1]), torch.Size([4]))

In [114]:
# firts pixel value in the first row of the first color channel of the first image
tb[0][0][0][0], tb[0][0][0][0].shape

(tensor(1), torch.Size([]))

In [117]:
# flatten the entire batch, so best for the CNN, we want to flatten each image within a batch
tb.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [118]:
# keep the dim=0 (the batch as is, only flatten along the dim=1, which is the color channel)
tb.flatten(start_dim=1), tb.flatten(start_dim=1).shape

(tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]]),
 torch.Size([3, 16]))

In [126]:
tb.reshape(3,-1), tb.reshape(3,-1).shape

(tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]]),
 torch.Size([3, 16]))

In [26]:
x = torch.rand(4,4)
print(x)
print(x.shape)
print(x.size())

tensor([[0.8615, 0.4939, 0.6771, 0.2069],
        [0.5140, 0.3477, 0.0595, 0.6300],
        [0.7064, 0.4010, 0.7143, 0.4969],
        [0.3247, 0.6225, 0.4621, 0.5195]])
torch.Size([4, 4])
torch.Size([4, 4])


In [27]:
y = x.view(16) # 1-d vector of 16 values
print(y)
print(y.size())

tensor([0.8615, 0.4939, 0.6771, 0.2069, 0.5140, 0.3477, 0.0595, 0.6300, 0.7064,
        0.4010, 0.7143, 0.4969, 0.3247, 0.6225, 0.4621, 0.5195])
torch.Size([16])


In [28]:
y = x.view(-1, 8) # 2-d vector of 2 x 8
print(y)
print(y.size())

tensor([[0.8615, 0.4939, 0.6771, 0.2069, 0.5140, 0.3477, 0.0595, 0.6300],
        [0.7064, 0.4010, 0.7143, 0.4969, 0.3247, 0.6225, 0.4621, 0.5195]])
torch.Size([2, 8])


### Convert from Numpy <--> Tensor

In [33]:
a = torch.ones(5)
print(a)
# convert tensor to numpy
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


### Caveat:

Both tensor `a` and numpy arrayh `b` point to the same memory location. 
Any inplace operations to either variable type will effect the other.
This side effect is only on CPUs,not GPUs. So for on cuda, this will 
not affect the underlying memory location as they will be at different locations.

In [34]:
a.add_(2) # change a in place by adding 2 to i
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


### The reverse

In [36]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [37]:
a += 2
print(a)
print(b)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
