In [29]:
import torch
import numpy as np

In [6]:
# create two rand 2 x 2 tensors 
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.7361, 0.1451],
        [0.6354, 0.0369]])
tensor([[0.9537, 0.0913],
        [0.4191, 0.4927]])


### Tensor torch common math operatitons:add, sub, mul, div etc

In [7]:
# do element wise addition of the two tensors
z = x + y
print(z)

tensor([[1.6898, 0.2364],
        [1.0545, 0.5296]])


In [8]:
z = torch.add(x,y)
print(z)

tensor([[1.6898, 0.2364],
        [1.0545, 0.5296]])


In [9]:
# do element wise tensor multiplication
m = x * y
print(m)

tensor([[0.7020, 0.0133],
        [0.2663, 0.0182]])


In [10]:
m = torch.mul(x,y)
print(m)

tensor([[0.7020, 0.0133],
        [0.2663, 0.0182]])


In [11]:
# do element wise division
d = x / y
print(d)

tensor([[0.7719, 1.5894],
        [1.5161, 0.0749]])


In [13]:
d = torch.div(x,y)
print(d)

tensor([[0.7719, 1.5894],
        [1.5161, 0.0749]])


In [14]:
s = x - y
print(s)

tensor([[-0.2175,  0.0538],
        [ 0.2163, -0.4558]])


In [16]:
s = torch.sub(x,y)
print(s)

tensor([[-0.2175,  0.0538],
        [ 0.2163, -0.4558]])


### Common slice operations

In [17]:
x = torch.rand(5,3)
print(x)

tensor([[0.2846, 0.3282, 0.1154],
        [0.7743, 0.7224, 0.5586],
        [0.5214, 0.3714, 0.5913],
        [0.8415, 0.3570, 0.7835],
        [0.8826, 0.3503, 0.9242]])


In [18]:
# print all rows and only the 0th column
print(x[:, 0])

tensor([0.2846, 0.7743, 0.5214, 0.8415, 0.8826])


In [23]:
# print all only row 1 and all columns
print(x[1, :])

tensor([0.7743, 0.7224, 0.5586])


In [21]:
# index into elemen [1,1], returns a tensor
# .item() returns the value. You can only use item() on a tensor with a single value
print(x[1,1])
print(x[1,1].item())

tensor(0.7224)
0.722439706325531


### Reshaping a tensor

In [26]:
x = torch.rand(4,4)
print(x)
print(x.shape)
print(x.size())

tensor([[0.8615, 0.4939, 0.6771, 0.2069],
        [0.5140, 0.3477, 0.0595, 0.6300],
        [0.7064, 0.4010, 0.7143, 0.4969],
        [0.3247, 0.6225, 0.4621, 0.5195]])
torch.Size([4, 4])
torch.Size([4, 4])


In [27]:
y = x.view(16) # 1-d vector of 16 values
print(y)
print(y.size())

tensor([0.8615, 0.4939, 0.6771, 0.2069, 0.5140, 0.3477, 0.0595, 0.6300, 0.7064,
        0.4010, 0.7143, 0.4969, 0.3247, 0.6225, 0.4621, 0.5195])
torch.Size([16])


In [28]:
y = x.view(-1, 8) # 2-d vector of 2 x 8
print(y)
print(y.size())

tensor([[0.8615, 0.4939, 0.6771, 0.2069, 0.5140, 0.3477, 0.0595, 0.6300],
        [0.7064, 0.4010, 0.7143, 0.4969, 0.3247, 0.6225, 0.4621, 0.5195]])
torch.Size([2, 8])


### Convert from Numpy <--> Tensor

In [33]:
a = torch.ones(5)
print(a)
# convert tensor to numpy
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


### Caveat:

Both tensor `a` and numpy arrayh `b` point to the same memory location. 
Any inplace operations to either variable type will effect the other.
This side effect is only on CPUs,not GPUs. So for on cuda, this will 
not affect the underlying memory location as they will be at different locations.

In [34]:
a.add_(2) # change a in place by adding 2 to i
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


### The reverse

In [36]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [37]:
a += 2
print(a)
print(b)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
