In [1]:
import numpy as np
import math

import torch
import torchvision
from torch.utils.data import Dataset, DataLoader

In [2]:
class FahrenheitTemperatures(Dataset):
    def __init__(self, start=-212, stop=10512, step=2):
        super(FahrenheitTemperatures, self).__init__()
        
        # Intialize local variables and covert them into tensors
        self.X = torch.from_numpy(np.arange(start, stop, step, dtype=float))
        self.y = torch.from_numpy(np.array([self._f2c(f) for f in self.X], dtype=float))
        self.X_p = torch.from_numpy(np.arange(212, 170, -5, dtype=float))
        self.n_samples = self.X.shape[0]
        
    def __getitem__(self, index):
        # support indexing such that dataset[i] can be used to get i-th sample
        # implement this python function for indexing
        return self.X[index], self.y[index]
        
        
    def __len__(self):
        # we can call len(dataset) to return the size, so this can be used
        # as an iterator
        return self.n_samples
    
    def _f2c(sel,f) -> float:
        return (f - 32) * 5.0/9.0

In [3]:
# Let's now access our dataset
dataset =FahrenheitTemperatures()
first_dataset = dataset[0]
features, labels = first_dataset
print('Fahrenheit: {:.2f}'.format(features))
print('Celcius   : {:.2f}'.format(labels))

Fahrenheit: -212.00
Celcius   : -135.56


In [4]:
# Now we can use the dataloader and iterator in a training loop

num_epochs = 2
batch_size = 4
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/batch_size)

print('Number of samples: {}'.format(total_samples))
print('Number of iterations: {}'.format(n_iterations))

Number of samples: 5362
Number of iterations: 1341


In [5]:
# Let's try Dataloader class and make this into an iterator and access the data as above
dataloader = DataLoader(dataset=dataset, batch_size=4, shuffle=True)

dataiter = iter(dataloader)
data = dataiter.next()
feartures, labels = data

# since we specified our batch size to be 4, we'll see four features and labels
print('Fahrenheit: {}'.format(features))
print('Celcius   : {}'.format(labels))

Fahrenheit: -212.0
Celcius   : tensor([4913.3333, 3398.8889, 5362.2222, 5694.4444], dtype=torch.float64)


In [7]:
# let's do a dummy training loop

for epoch in range(num_epochs):
    # iterate over our dataloader in batches
    # Because we have implemented our Dataset class with __getitem__ and __len__, we
    # can iterate over it
    for i, (inputs, labels) in enumerate(dataloader):
        # forward and backward pass, update gradients, and zero them out
        # Run your training process
        if (i+1) % 400 == 0:
            print(f'Epoch: {epoch+1}/{num_epochs}, Step {i+1}/{n_iterations}| Inputs {inputs.shape} | Labels {labels.shape}, Tensors {inputs}')      

Epoch: 1/2, Step 400/1341| Inputs torch.Size([4]) | Labels torch.Size([4]), Tensors tensor([1668., 5680.,  520., 2916.], dtype=torch.float64)
Epoch: 1/2, Step 800/1341| Inputs torch.Size([4]) | Labels torch.Size([4]), Tensors tensor([ 3068., 10474., 10138.,  9616.], dtype=torch.float64)
Epoch: 1/2, Step 1200/1341| Inputs torch.Size([4]) | Labels torch.Size([4]), Tensors tensor([8264., 9876., 6564., 3120.], dtype=torch.float64)
Epoch: 2/2, Step 400/1341| Inputs torch.Size([4]) | Labels torch.Size([4]), Tensors tensor([6184.,  650., 1674.,  316.], dtype=torch.float64)
Epoch: 2/2, Step 800/1341| Inputs torch.Size([4]) | Labels torch.Size([4]), Tensors tensor([7986., 2532., 5888., 7944.], dtype=torch.float64)
Epoch: 2/2, Step 1200/1341| Inputs torch.Size([4]) | Labels torch.Size([4]), Tensors tensor([2570., 4188., 8420., 6810.], dtype=torch.float64)


In [113]:
X = torch.from_numpy(np.arange(1., 100.))
y = torch.from_numpy(np.array([(x*2) for x in X]))

In [110]:
X

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.,
        29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42.,
        43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55., 56.,
        57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70.,
        71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83., 84.,
        85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95., 96., 97., 98.,
        99.], dtype=torch.float64)

In [111]:
y

tensor([  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,
         26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,  48.,
         50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,  72.,
         74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,
         98., 100., 102., 104., 106., 108., 110., 112., 114., 116., 118., 120.,
        122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142., 144.,
        146., 148., 150., 152., 154., 156., 158., 160., 162., 164., 166., 168.,
        170., 172., 174., 176., 178., 180., 182., 184., 186., 188., 190., 192.,
        194., 196., 198.], dtype=torch.float64)

In [118]:
x_data = torch.Tensor([[1.0], [2.0], [3.0]])
x_data, x_data.shape

(tensor([[1.],
         [2.],
         [3.]]),
 torch.Size([3, 1]))

In [119]:
x = X.view(-1, 1)
x, x.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.],
         [13.],
         [14.],
         [15.],
         [16.],
         [17.],
         [18.],
         [19.],
         [20.],
         [21.],
         [22.],
         [23.],
         [24.],
         [25.],
         [26.],
         [27.],
         [28.],
         [29.],
         [30.],
         [31.],
         [32.],
         [33.],
         [34.],
         [35.],
         [36.],
         [37.],
         [38.],
         [39.],
         [40.],
         [41.],
         [42.],
         [43.],
         [44.],
         [45.],
         [46.],
         [47.],
         [48.],
         [49.],
         [50.],
         [51.],
         [52.],
         [53.],
         [54.],
         [55.],
         [56.],
         [57.],
         [58.],
         [59.],
         [60.],
         [61.],
         [62.],
        

In [121]:
torch.arange(1, 5).view(-1, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [133]:
X = torch.arange(1, 10, dtype=np.float).view(-1, 1)
y = torch.from_numpy(np.array([(x * 2) for x in X], dtype=np.float)).view(-1, 1)

In [134]:
X

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]], dtype=torch.float64)

In [135]:
y

tensor([[ 2.],
        [ 4.],
        [ 6.],
        [ 8.],
        [10.],
        [12.],
        [14.],
        [16.],
        [18.]], dtype=torch.float64)