In [50]:
import os

import torch
import mlflow
import mlflow.pytorch
import numpy as np

In [51]:
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

In [57]:
# X data
#x_data = torch.Tensor([[1.0], [2.0], [3.0], [4.0], [5.0]])
x_data = torch.arange(1.0, 7.0).view(-1, 1)
# Y data with its expected value: labels
#y_data = torch.Tensor([[2.0], [4.0], [6.0], [8.0], [10.0]])
y_data = torch.from_numpy(np.array([2*x for x in x_data])).view(-1, 1)

In [58]:
x_data, x_data.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.]]),
 torch.Size([6, 1]))

In [59]:
y_data, y_data.shape

(tensor([[ 2.],
         [ 4.],
         [ 6.],
         [ 8.],
         [10.],
         [12.]]),
 torch.Size([6, 1]))

In [60]:
# Partial Model example modified from Sung Kim
class Model(torch.nn.Module):
    def __init__(self):
       super().__init__()
       self.linear = torch.nn.Linear(1, 1)  # One in and one out
    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred

In [61]:
# our model
model = Model()
criterion = torch.nn.MSELoss(size_average=False)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
# Training loop
epochs= 500
for epoch in range(epochs):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x_data)
    # Compute and print loss
    loss = criterion(y_pred, y_data)
    #Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if (epoch + 1) % 200 == 0:
        print('Epoch: {}/{}, loss: {:.4f}'.format(epoch + 1., epochs, loss.data.item()))

Epoch: 200.0/500, loss: 0.0003
Epoch: 400.0/500, loss: 0.0000


In [62]:
# After training
for hv in [4.0, 5.0, 6.0]:
    hour_var = torch.Tensor([[hv]])
    y_pred = model(hour_var)
    print("predict (after training)",  hv, model(hour_var).data[0][0])

predict (after training) 4.0 tensor(8.0000)
predict (after training) 5.0 tensor(10.0000)
predict (after training) 6.0 tensor(12.0000)


In [41]:
x_data = torch.Tensor([[1.0], [2.0], [3.0], [4.0], [5.0]])
X = torch.arange(1, 6, dtype=torch.float32).view(-1, 1)
X, X.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.]]),
 torch.Size([5, 1]))

In [13]:
x_data, x_data.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.]]),
 torch.Size([5, 1]))

In [14]:
y = torch.from_numpy(np.array([2*x for x in X])).view(-1,1)
y, y.shape

(tensor([[ 2.],
         [ 4.],
         [ 6.],
         [ 8.],
         [10.]]),
 torch.Size([5, 1]))